/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Auth;

import com.formdev.flatlaf.FlatLightLaf;
import Config.DB;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.util.prefs.Preferences;
import javax.swing.ImageIcon;
import org.w3c.dom.events.MouseEvent;
import java.sql.ResultSet;
import javax.swing.UIManager;
import com.formdev.flatlaf.FlatClientProperties;
import org.json.JSONArray;

/**
 *
 * @author Pixel
 */
public class login extends javax.swing.JFrame {

    static String getString(String nama) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    static int getInt(String id) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    Preferences userPreferences = Preferences.userNodeForPackage(login.class);

    public void rememberMe() {
        userPreferences.put("Username", username.getText());
        String storedUsername = userPreferences.get("Username", null);
        if (storedUsername != null) {
            System.out.println(storedUsername);
        } else {
            System.out.println("Hayabusa");
        }
    }

    private ImageIcon images(String path, int WIDTH, int HEIGHT) {
        ImageIcon img = new ImageIcon(getClass().getResource(path));
        Image image = (img).getImage().getScaledInstance(WIDTH, HEIGHT, Image.SCALE_SMOOTH);
        img = new ImageIcon(image);
        return img;
    }

    /**
     * Creates new form login
     */
    public login() {
      
        initComponents();
        ImageIcon img = images("/Asset_login/login-anyaran.png", 380, 380);
        login_image.setIcon(img);

        ImageIcon keluar = images("/Asset_login/logout_exit.png", 36, 36);
        exit.setIcon(keluar);

        ImageIcon MINI = images("/Asset_login/minimize (2).png", 32, 32);
        minimize.setIcon(MINI);
        ImageIcon logo = images("/Assets/logof/logoapp.png", 200, 200);
        logoappss.setIcon(logo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        login_image = new javax.swing.JLabel();
        logoappss = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        exit = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        username = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KASIR KEREN");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(720, 512));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(58, 98, 215));
        jPanel1.setPreferredSize(new java.awt.Dimension(405, 256));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Copyright © 2023 Namaku");

        login_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(login_image, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(login_image, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(57, 57, 57))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 529));

        logoappss.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoappss.setForeground(new java.awt.Color(51, 51, 255));
        jPanel2.add(logoappss, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 210, 70));

        jLabel1.setFont(new java.awt.Font("Leelawadee", 0, 16)); // NOI18N
        jLabel1.setText("Welcome to ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("SISKA");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));

        jButton1.putClientProperty(FlatClientProperties.STYLE,"arc:50");
        jButton1.setBackground(new java.awt.Color(58, 98, 215));
        jButton1.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.setToolTipText("Login");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setMaximumSize(new java.awt.Dimension(58, 20));
        jButton1.setMinimumSize(new java.awt.Dimension(58, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 251, 34));

        password.putClientProperty(FlatClientProperties.STYLE,"arc:50; showRevealButton:true");
        password.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT,"Password");
        password.setMinimumSize(new java.awt.Dimension(58, 20));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 250, 34));

        exit.setToolTipText("Exit\n");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 40, 30));

        minimize.setToolTipText("Minimize");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 30, 30));

        username.putClientProperty(FlatClientProperties.STYLE,"arc:50");
        username.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT,"Username");
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 250, 34));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
//       if(password.getText().equals("Password")){
//            password.setText("");
//        }
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
//        if(password.getText().equals("")){
//            password.setText("Password");
//        }
    }//GEN-LAST:event_passwordFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loginCheck();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
//        int hasil = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin keluar?");
//        if (hasil = 0){
//            
//        }
        System.exit(0);
        rememberMe();
    }//GEN-LAST:event_exitMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(login.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginCheck();

        }
    }//GEN-LAST:event_passwordKeyPressed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        // TODO add your handling code here:
        char user = evt.getKeyChar();
        if (!Character.isLetterOrDigit(user)) {
            evt.consume();
        }
    }//GEN-LAST:event_usernameKeyTyped

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            UIManager.put("Button.arc", 15);
            UIManager.put("TextComponent.arc", 15);

        } catch (Exception e) {
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new login().setVisible(true);
            }
        });

        System.setProperty("sun.java2d,uiScale.enabled", "false");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel login_image;
    private javax.swing.JLabel logoappss;
    private javax.swing.JLabel minimize;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    private void loginCheck() {
        DB.query("SELECT * FROM users;");
        try {
            if (username.getText().isEmpty()) {
                //else if #1
                JOptionPane.showMessageDialog(null, "Username tidak boleh kosong!");
            } else if (password.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Password tidak boleh kosong!");
            } else {
                ResultSet login = DB.query("SELECT * FROM users where username ='" + username.getText() + "'");
                if (login.next()) {
                    //else if #2
                    if (password.getText().equals(login.getString("password"))) {
                        //else if 3
                        Preferences userPreferences = Preferences.userNodeForPackage(login.class);
                        String[] dataArray = {login.getString("id"),login.getString("nama"),login.getString("username"),login.getString("role")};
                        JSONArray jsonArray = new JSONArray(dataArray);
                        userPreferences.put("localLogin", jsonArray.toString());
                        dispose();
                        new SaldoKasAwal().setVisible(true);
                    } else {
                        //
                        JOptionPane.showMessageDialog(rootPane, "Password Salah");
                        System.out.println("Password Salah");

                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "User Tidak Ditemukan");
                    System.out.println("User Tidak Ditemukan");
                }

            }
        } catch (Exception e) {

        }
    }
//    private void setShowHidePassword() {
//        eye1.addMouseListener(new MouseAdapter() {
//            public void mouseClicked(MouseEvent e) {
//                eye1.setVisible(false);
//                eye2.setVisible(true);
//                password.setEchoChar((char) 0);
//            }
//        });
//
//        eye2.addMouseListener(new MouseAdapter() {
//            public void mouseClicked(MouseEvent e) {
//                eye1.setVisible(true);
//                eye2.setVisible(false);
//                password.setEchoChar('*');
//            }
//        });
//    }
}
