/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Auth;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import Config.DB;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import org.json.JSONArray;
import org.json.JSONException;

/**
 *
 * @author Pixel
 */
public class SaldoKasAwal extends javax.swing.JFrame {

    /**
     * Creates new form SaldoKasAwal
     */
    private int id;

    public SaldoKasAwal() {
        initComponents();
       Preferences userPreferences = Preferences.userNodeForPackage(SaldoKasAwal.class);
       

        try {
            String datalogin = userPreferences.get("localLogin", null);

            if (datalogin != null) {

                JSONArray retrievedArray = new JSONArray(datalogin);
                id = Integer.parseInt(retrievedArray.getString(0));         
            } else {
                new login().setVisible(true);
            }
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputkas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logout_saldoo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(58, 98, 215));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 512));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputkas.putClientProperty(FlatClientProperties.STYLE,"arc:550");
        inputkas.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT,"Masukkan Saldo Kas Awal");
        inputkas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        inputkas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputkas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputkasActionPerformed(evt);
            }
        });
        inputkas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputkasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputkasKeyTyped(evt);
            }
        });
        jPanel1.add(inputkas, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 197, 450, 60));

        jButton1.putClientProperty(FlatClientProperties.STYLE,"arc:550");
        jButton1.setBackground(new java.awt.Color(66, 133, 244));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LANJUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 275, 450, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SALDO KAS AWAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 147, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sebelum lanjut masukkan saldo kas awal");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 353, -1, -1));

        logout_saldoo.setIcon(new FlatSVGIcon("Asset_login/logout_saldo.svg"));
        logout_saldoo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_saldoo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_saldooMouseClicked(evt);
            }
        });
        jPanel1.add(logout_saldoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       addsaoldo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inputkasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputkasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            addsaoldo();
        }
    }//GEN-LAST:event_inputkasKeyPressed

    private void inputkasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputkasKeyTyped
        char character = evt.getKeyChar();
        if (!Character.isDigit(character) || inputkas.getText().length() >= 7 || Character.isWhitespace(character)) {
            evt.consume();
        }
    }//GEN-LAST:event_inputkasKeyTyped

    private void inputkasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputkasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputkasActionPerformed

    private void logout_saldooMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_saldooMouseClicked
        // TODO add your handling code here:
        Preferences userPreferences = Preferences.userNodeForPackage(login.class);
        userPreferences.put("nama_user", "");
        userPreferences.putInt("id_user", 0);
        dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_logout_saldooMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaldoKasAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaldoKasAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaldoKasAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaldoKasAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            UIManager.put("Button.arc", 900);
            UIManager.put("TextComponent.arc", 900);
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaldoKasAwal().setVisible(true);
            }
        });
    }

    private void addsaoldo(){
         Preferences userPreferences = Preferences.userNodeForPackage(SaldoKasAwal.class);

        if (inputkas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Saldo Awal tidak boleh Kosong!");
        } else if (!inputkas.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Karakter harus bersifat Numerik!");
            inputkas.setText("");
        } else {
            try {
                dispose();
                new Main.Main().setVisible(true);
                String inputkastxt = inputkas.getText();

                int jumlah = DB.query2("INSERT INTO shift(id_user, saldo_awal_kas, waktu_buka) VALUES (" + id + ",'" + inputkastxt + "', NOW())");
                ResultSet p = DB.query("select id,tanggal_dibuat from shift order by id desc limit 1");
              
                if (p.next()) {
                     System.out.println(p.getString("tanggal_dibuat"));
                    String[] dataArray = {p.getString("id"), inputkastxt, p.getString("tanggal_dibuat")};
                   
                    JSONArray jsonArray = new JSONArray(dataArray);
                    userPreferences.put("datashift", jsonArray.toString());
                    System.out.println("Saldo berhasil ditambahkan.");
                }

            } catch (JSONException ex) {
                Logger.getLogger(SaldoKasAwal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(SaldoKasAwal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputkas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logout_saldoo;
    // End of variables declaration//GEN-END:variables
}
